apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ywep5hrp2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-66f41fdf6a.l4eo.p3.openshiftapps.com/rhtap/rhtap-qe-python:430a34e759fe7f62447be3f5cdc634338869ce0e@sha256:3102e711a53de482fa057585ad70c14a446aa3d80d19fff6a20beca56a240c13
          name: container-image
